spring:
  application:
    name: brt-service
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://config-server:8888
    function:
      definition: cdrConsumer
    stream:
      bindings:
        cdrConsumer-in-0:
          destination: cdr-exchange
          group: brt-group
          content-type: application/json
          consumer:
            max-attempts: 3
      rabbit:
        bindings:
          cdrConsumer-in-0:
            consumer:
              binding-routing-key: cdr-routing-key
              auto-bind-dlq: true
              dlq-ttl: 5000
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

server:
  port: 8081
