services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  commutator:
    build:
      context: commutator-service/
    container_name: baby-billing-commutator
    ports:
      - "8080:8080"
    environment:
      H2_USERNAME: "su"
      H2_PASSWORD: "password"
      H2_URL: "jdbc:h2:mem:commutator-service"
      RABBIT_HOST: "rabbitmq"
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "password"
      RABBIT_PORT: "5672"
    depends_on:
      - rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local