services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  eureka:
    build:
      context: eureka-server/
    container_name: eureka
    restart: always
    ports:
      - "8761:8761"

  brt-db:
    image: postgres:latest
    container_name: brt-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "brt"
    volumes:
      - brt-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  brt:
    build:
      context: brt-service/
    container_name: baby-billing-brt
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "brt"
      RABBIT_HOST: "brt-db"
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "password"
      RABBIT_PORT: "5672"
    depends_on:
      - brt-db
      - rabbitmq
      - eureka

  commutator:
    build:
      context: commutator-service/
    container_name: baby-billing-commutator
    ports:
      - "8080:8080"
    environment:
      H2_USERNAME: "su"
      H2_PASSWORD: "password"
      H2_URL: "jdbc:h2:mem:commutator-service"
      RABBIT_HOST: "rabbitmq"     
      RABBIT_USERNAME: "admin"
      RABBIT_PASSWORD: "password"
      RABBIT_PORT: "5672"         
    depends_on:
      - rabbitmq
      - brt


volumes:
  rabbitmq-lib:
    driver: local	
  rabbitmq-log:
    driver: local
  brt-data:
    driver: local